name: interactive_chart
description: A candlestick chart that supports hand gestures such as pinch-to-zoom and panning.
version: 0.3.5
homepage: https://github.com/h65wang/flutter-interactive-chart

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter
